<main class="page service-page">
    <section class="clean-block clean-services dark">
        <div class="container">
            <div class="block-heading">
                <h2 class="text-info">Pronti, Partenza, Via!!!!</h2>

            </div>
            <div class="block-heading">
                <h5 class="text-info">Clicca un pulsante...</h5>
            </div>
            <div class="row">
                <div class="col-md-3 col-lg-4">

                    <div class="card">

                        <div class="mb-4"><a class="btn btn-primary border rounded" role="button" href="<?=$this->url('pagina1')?>">Vai a pagina 1</a></div>
                    </div>

                </div>
                <div class="col-md-3 col-lg-4">

                    <div class="card">

                        <div class="mb-4"><a class="btn btn-primary border rounded" role="button" href="<?=$this->url('pagina2')?>">Vai a pagina 2</a></div>
                    </div>

                </div>
                <div class="col-md-3 col-lg-4">

                    <div class="card">

                        <div class="mb-4"><a class="btn btn-primary border rounded" role="button" href="<?=$this->url('pagina3')?>">Vai a pagina 3</a></div>
                    </div>

                </div>

                <div class="col-md-3 col-lg-4">

                    <div class="card">

                        <div class="mb-4"><a class="btn btn-primary border rounded" role="button" href="<?=$this->url('compila_mail')?>">Compila la mail</a></div>
                    </div>

                </div>
                <div class="col-md-3 col-lg-4">

                    <div class="card">

                        <div class="mb-4"><a class="btn btn-primary border rounded" role="button" href="<?=$this->url('invia_mail')?>">Invia la mail</a></div>
                    </div>

                </div>
            </div>
        </div>
        <div class="container mt-3">
            <p class="text-center">Se hai dubbi sulla compilazione della mail, chiama il numero <?=$telefono_info ?? ''?></p>
        </div>
    </section>
</main>
