<main class="page contact-us-page">
    <section class="clean-block clean-form dark">
        <div class="container">
            <div class="block-heading">
                <h2 class="text-info">Mail inviata</h2>
                <p class="info-short">La tua mail &egrave; stata inoltrata, attendi una nostra comunicazione.</p>
                <p class="info-short mt-4"><em>Grazie per averci contattato!</em></p>
            </div>
            <div class="text-center mt-5 mb-5"><a class="btn btn-primary" role="button" href="<?=$this->url('home')?>">Torna alla Homepage</a></div>
        </div>
    </section>
</main>