version: "3"

services:

  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: docker-partenza
    volumes:
      - .:/var/www/html/partenza
      - .docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - .docker/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini

    ports:
      - 80:80

