<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            Partenza\Action\CompilaMailAction::class => Partenza\Action\CompilaMailActionFactory::class,
            Partenza\Action\IndexAction::class => Partenza\Action\IndexActionFactory::class,
            Partenza\Action\InviaMailAction::class => Partenza\Action\InviaMailActionFactory::class,
            Partenza\Action\Pagina1Action::class => Partenza\Action\Pagina1ActionFactory::class,
            Partenza\Action\Pagina2Action::class => Partenza\Action\Pagina2ActionFactory::class,
            Partenza\Action\Pagina3Action::class => Partenza\Action\Pagina3ActionFactory::class,
            Partenza\Middleware\AnalizzaMailMiddleware::class => Partenza\Middleware\AnalizzaMailMiddlewareFactory::class,
            Partenza\Middleware\ConfigAppMiddleware::class => Partenza\Middleware\ConfigAppMiddlewareFactory::class,
            Partenza\Middleware\SendMailMiddleware::class => Partenza\Middleware\SendMailMiddlewareFactory::class,
            Partenza\Middleware\UrlHelperMiddleware::class => Partenza\Middleware\UrlHelperMiddlewareFactory::class,
        ],
    ],
];
